CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607155713_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "MiddleName" text NOT NULL,
        "LastName" text NOT NULL,
        "Address" text NOT NULL,
        "Contact" text NOT NULL,
        "BirthMonth" text NOT NULL,
        "BirthDate" text NOT NULL,
        "BirthYear" text NOT NULL,
        "Username" text NOT NULL,
        "Email" text NOT NULL,
        "Password" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607155713_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260607155713_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607160428_AddRidersAndMerchants') THEN
    CREATE TABLE "Merchants" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "BusinessName" text NOT NULL,
        "OwnerFirstName" text NOT NULL,
        "OwnerLastName" text NOT NULL,
        "BusinessAddress" text NOT NULL,
        "BusinessContact" text NOT NULL,
        "BusinessEmail" text NOT NULL,
        "BIRFormPath" text NOT NULL,
        "DTICertificatePath" text NOT NULL,
        "BarangayClearancePath" text NOT NULL,
        "GCContact" text NOT NULL,
        CONSTRAINT "PK_Merchants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Merchants_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607160428_AddRidersAndMerchants') THEN
    CREATE TABLE "Riders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "LicensePath" text NOT NULL,
        "IDPath" text NOT NULL,
        "ORCRPath" text NOT NULL,
        "AgreementPath" text NOT NULL,
        "FrontVehiclePath" text NOT NULL,
        "SideVehiclePath" text NOT NULL,
        "GCContact" text NOT NULL,
        CONSTRAINT "PK_Riders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Riders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607160428_AddRidersAndMerchants') THEN
    CREATE INDEX "IX_Merchants_UserId" ON "Merchants" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607160428_AddRidersAndMerchants') THEN
    CREATE INDEX "IX_Riders_UserId" ON "Riders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260607160428_AddRidersAndMerchants') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260607160428_AddRidersAndMerchants', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "RiderId" integer,
        "MerchantId" integer NOT NULL,
        "Status" text NOT NULL,
        "Subtotal" numeric(10,2) NOT NULL,
        "DeliveryFee" numeric(10,2) NOT NULL,
        "Discount" numeric(10,2) NOT NULL,
        "TotalAmount" numeric(10,2) NOT NULL,
        "PaymentMethod" text NOT NULL,
        "DeliveryAddress" text NOT NULL,
        "CustomerContact" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "DeliveredAt" timestamp with time zone,
        "CancelledAt" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Merchants_MerchantId" FOREIGN KEY ("MerchantId") REFERENCES "Merchants" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Riders_RiderId" FOREIGN KEY ("RiderId") REFERENCES "Riders" ("Id"),
        CONSTRAINT "FK_Orders_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ItemName" text NOT NULL,
        "Quantity" integer NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    CREATE INDEX "IX_Orders_MerchantId" ON "Orders" ("MerchantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    CREATE INDEX "IX_Orders_RiderId" ON "Orders" ("RiderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609054217_AddOrdersTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609054217_AddOrdersTable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609055014_AddRiderStatusAndPlateNumber') THEN
    ALTER TABLE "Riders" ADD "PlateNumber" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609055014_AddRiderStatusAndPlateNumber') THEN
    ALTER TABLE "Riders" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609055014_AddRiderStatusAndPlateNumber') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609055014_AddRiderStatusAndPlateNumber', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609055810_MakePlateNumberNullable') THEN
    ALTER TABLE "Riders" ALTER COLUMN "PlateNumber" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609055810_MakePlateNumberNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609055810_MakePlateNumberNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609060849_AddRiderCreatedAt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609060849_AddRiderCreatedAt', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609061158_MakeMiddleNameNullable') THEN
    ALTER TABLE "Users" ALTER COLUMN "MiddleName" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609061158_MakeMiddleNameNullable') THEN
    ALTER TABLE "Riders" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609061158_MakeMiddleNameNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609061158_MakeMiddleNameNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609154652_AddMerchantStatusCategoryCreatedAt') THEN
    ALTER TABLE "Merchants" ADD "Category" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609154652_AddMerchantStatusCategoryCreatedAt') THEN
    ALTER TABLE "Merchants" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609154652_AddMerchantStatusCategoryCreatedAt') THEN
    ALTER TABLE "Merchants" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609154652_AddMerchantStatusCategoryCreatedAt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609154652_AddMerchantStatusCategoryCreatedAt', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609160442_MakeBirthFieldsNullable') THEN
    ALTER TABLE "Users" ALTER COLUMN "BirthYear" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609160442_MakeBirthFieldsNullable') THEN
    ALTER TABLE "Users" ALTER COLUMN "BirthMonth" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609160442_MakeBirthFieldsNullable') THEN
    ALTER TABLE "Users" ALTER COLUMN "BirthDate" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260609160442_MakeBirthFieldsNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260609160442_MakeBirthFieldsNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    ALTER TABLE "Riders" ADD "AgreementStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    ALTER TABLE "Riders" ADD "FrontVehicleStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    ALTER TABLE "Riders" ADD "IDStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    ALTER TABLE "Riders" ADD "LicenseStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    ALTER TABLE "Riders" ADD "ORCRStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    ALTER TABLE "Riders" ADD "SideVehicleStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610083330_AddRiderDocumentStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260610083330_AddRiderDocumentStatuses', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610084958_AddDocumentStatuses') THEN
    ALTER TABLE "Merchants" ADD "BIRFormStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610084958_AddDocumentStatuses') THEN
    ALTER TABLE "Merchants" ADD "BarangayClearanceStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610084958_AddDocumentStatuses') THEN
    ALTER TABLE "Merchants" ADD "DTICertificateStatus" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610084958_AddDocumentStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260610084958_AddDocumentStatuses', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610182057_AddUserRole') THEN
    ALTER TABLE "Users" ADD "Role" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610182057_AddUserRole') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260610182057_AddUserRole', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Riders_RiderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Users_CustomerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    DROP INDEX "IX_Riders_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    DROP INDEX "IX_Merchants_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Users" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Users" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Users" ADD "ProfileImagePath" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Riders" ADD "CurrentLatitude" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Riders" ADD "CurrentLongitude" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Riders" ADD "IsOnline" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Riders" ADD "VehicleType" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" ADD "AcceptedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" ADD "PickedUpAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" ADD "RiderNotes" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Merchants" ADD "ClosingTime" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Merchants" ADD "CoverImagePath" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Merchants" ADD "Latitude" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Merchants" ADD "LogoPath" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Merchants" ADD "Longitude" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Merchants" ADD "OpeningTime" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE TABLE "Customers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "DefaultDeliveryAddress" text,
        "DefaultLatitude" double precision,
        "DefaultLongitude" double precision,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Customers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE TABLE "CustomerAddresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "Label" text NOT NULL,
        "FullAddress" text NOT NULL,
        "Latitude" double precision,
        "Longitude" double precision,
        "IsDefault" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CustomerAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CustomerAddresses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE UNIQUE INDEX "IX_Riders_UserId" ON "Riders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE UNIQUE INDEX "IX_Merchants_UserId" ON "Merchants" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE INDEX "IX_CustomerAddresses_CustomerId" ON "CustomerAddresses" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    CREATE UNIQUE INDEX "IX_Customers_UserId" ON "Customers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Riders_RiderId" FOREIGN KEY ("RiderId") REFERENCES "Riders" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260720144510_MultiUserSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260720144510_MultiUserSchema', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727165317_AddCustomerGender') THEN
    ALTER TABLE "Users" ADD "Gender" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727165317_AddCustomerGender') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260727165317_AddCustomerGender', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729145913_AddGoogleAuth') THEN
    ALTER TABLE "Users" ALTER COLUMN "Password" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729145913_AddGoogleAuth') THEN
    ALTER TABLE "Users" ADD "GoogleId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729145913_AddGoogleAuth') THEN
    CREATE UNIQUE INDEX "IX_Users_GoogleId" ON "Users" ("GoogleId") WHERE "GoogleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729145913_AddGoogleAuth') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729145913_AddGoogleAuth', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731160522_AddStoreTable') THEN
    DROP TABLE IF EXISTS "Stores" CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731160522_AddStoreTable') THEN
    CREATE TABLE "Stores" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BusinessName" text NOT NULL,
        "BusinessAddress" text NOT NULL,
        "Category" text,
        "LogoPath" text,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Stores" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731160522_AddStoreTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731160522_AddStoreTable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731161106_FixOrderMerchantId') THEN

    DO $$
    BEGIN
      IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='Orders' and column_name='StoreId') THEN
          ALTER TABLE "Orders" RENAME COLUMN "StoreId" TO "MerchantId";
          ALTER INDEX "IX_Orders_StoreId" RENAME TO "IX_Orders_MerchantId";
          
          ALTER TABLE "Merchants" ADD COLUMN "ClosingTime" text;
          ALTER TABLE "Merchants" ADD COLUMN "CoverImagePath" text;
          ALTER TABLE "Merchants" ADD COLUMN "Latitude" double precision;
          ALTER TABLE "Merchants" ADD COLUMN "LogoPath" text;
          ALTER TABLE "Merchants" ADD COLUMN "Longitude" double precision;
          ALTER TABLE "Merchants" ADD COLUMN "OpeningTime" text;

          ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Merchants_MerchantId" FOREIGN KEY ("MerchantId") REFERENCES "Merchants" ("Id") ON DELETE CASCADE;
      END IF;
    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731161106_FixOrderMerchantId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731161106_FixOrderMerchantId', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802081304_AddLoginSecurityFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802081304_AddLoginSecurityFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802083046_UpdateLoginSecurityFields') THEN
    ALTER TABLE "Users" ADD "FailedLoginAttempts" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802083046_UpdateLoginSecurityFields') THEN
    ALTER TABLE "Users" ADD "LockoutEnd" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802083046_UpdateLoginSecurityFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802083046_UpdateLoginSecurityFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Users" DROP COLUMN "BirthDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Users" DROP COLUMN "BirthMonth";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Users" DROP COLUMN "BirthYear";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "AgreementPath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "AgreementStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "FrontVehiclePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "FrontVehicleStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "IDPath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "IDStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "LicensePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "LicenseStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "ORCRPath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "ORCRStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "SideVehiclePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Riders" DROP COLUMN "SideVehicleStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Merchants" DROP COLUMN "ClosingTime";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Merchants" DROP COLUMN "CoverImagePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Merchants" DROP COLUMN "Latitude";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Merchants" DROP COLUMN "LogoPath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Merchants" DROP COLUMN "Longitude";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Merchants" DROP COLUMN "OpeningTime";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Customers" DROP COLUMN "DefaultDeliveryAddress";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Customers" DROP COLUMN "DefaultLatitude";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Customers" DROP COLUMN "DefaultLongitude";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Users" ADD "DateOfBirth" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD "ClosingTime" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD "CoverImagePath" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD "Latitude" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD "Longitude" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD "MerchantId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD "OpeningTime" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "OrderItems" ADD "ProductId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StoreId" integer NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "Price" numeric(10,2) NOT NULL,
        "ImagePath" text,
        "IsAvailable" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    CREATE TABLE "RiderDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RiderId" integer NOT NULL,
        "DocumentType" text NOT NULL,
        "FilePath" text NOT NULL,
        "Status" text NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RiderDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RiderDocuments_Riders_RiderId" FOREIGN KEY ("RiderId") REFERENCES "Riders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    CREATE INDEX "IX_Stores_MerchantId" ON "Stores" ("MerchantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    CREATE INDEX "IX_Products_StoreId" ON "Products" ("StoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    CREATE INDEX "IX_RiderDocuments_RiderId" ON "RiderDocuments" ("RiderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "OrderItems" ADD CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    ALTER TABLE "Stores" ADD CONSTRAINT "FK_Stores_Merchants_MerchantId" FOREIGN KEY ("MerchantId") REFERENCES "Merchants" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804145923_NormalizeDatabase') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804145923_NormalizeDatabase', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814155036_AddAddressDetailFields') THEN
    ALTER TABLE "CustomerAddresses" ADD "ContactName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814155036_AddAddressDetailFields') THEN
    ALTER TABLE "CustomerAddresses" ADD "ContactPhone" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814155036_AddAddressDetailFields') THEN
    ALTER TABLE "CustomerAddresses" ADD "FloorUnit" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814155036_AddAddressDetailFields') THEN
    ALTER TABLE "CustomerAddresses" ADD "Notes" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814155036_AddAddressDetailFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260814155036_AddAddressDetailFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260816073730_AddProductCategory') THEN
    ALTER TABLE "Products" ADD "Category" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260816073730_AddProductCategory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260816073730_AddProductCategory', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260816080405_MakeStoreMerchantNullable') THEN
    ALTER TABLE "Stores" DROP CONSTRAINT "FK_Stores_Merchants_MerchantId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260816080405_MakeStoreMerchantNullable') THEN
    ALTER TABLE "Stores" ALTER COLUMN "MerchantId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260816080405_MakeStoreMerchantNullable') THEN
    ALTER TABLE "Stores" ADD CONSTRAINT "FK_Stores_Merchants_MerchantId" FOREIGN KEY ("MerchantId") REFERENCES "Merchants" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260816080405_MakeStoreMerchantNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260816080405_MakeStoreMerchantNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

